# Generated by Django 5.0.6 on 2024-05-27 07:39

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default=core.models.generate_secret_token, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='http_method',
            field=models.CharField(max_length=10),
        ),
    ]
